dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: jx-camel-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: jx-oms-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: jx-oms-demo-2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
